name: Deploy to VPS and Shared Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/discourse-app
            git pull origin main
            npm ci
            rm -rf dist/*
            npm run build
            pm2 restart discourse-app

  deploy-shared-hosting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Clean previous build
        run: rm -rf dist/* public/*

      - name: Build project
        run: |
          npm run build
          date > dist/build-timestamp.txt
          echo "Build completed at $(date)" > dist/build-info.txt
          echo "Build completed at $(date)" > dist/build-info.txt

      - name: Prepare public folder
        run: |
          echo "=== Preparing public folder ==="
          mkdir -p public
          cp -r dist/* public/
          cp -r src public/src/
          # Add cache-busting timestamp to index.html
          sed -i "s|</head>|<meta name=\"build-time\" content=\"$(date)\" />\n</head>|" public/index.html
          echo "=== Public folder contents ==="
          ls -la public/
          echo "=== Public/src contents ==="
          ls -la public/src/

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: home/u514166296/domains/thediscourse.ai/public_html/
          port: 21
          dangerous-clean-slate: true

      - name: Verify deployed build (optional)
        run: curl -s https://${{ secrets.FTP_SERVER }}/build-timestamp.txt || echo "Timestamp not found"
        
      - name: Clear browser cache headers
        run: |
          echo "=== Adding cache-busting headers ==="
          # Create a .htaccess addition for cache busting
          cat >> public/.htaccess << 'EOF'
          
          # Force cache refresh for development
          <IfModule mod_headers.c>
            <FilesMatch "\.(html|htm)$">
              Header always set Cache-Control "no-cache, no-store, must-revalidate"
              Header always set Pragma "no-cache"
              Header always set Expires "0"
            </FilesMatch>
          </IfModule>
          EOF

      - name: Clear cache headers (optional)
        run: |
          echo "=== Clearing cache for main assets ==="
          curl -X PURGE https://${{ secrets.FTP_SERVER }}/index.html || echo "PURGE not supported"
          curl -X PURGE https://${{ secrets.FTP_SERVER }}/assets/ || echo "PURGE not supported"
